### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by cmaumet** [acm-rep/2024#22]
Hi,

I am attaching here the logos of the different funders. Would it be possible to add them to the website? Thank you! 

Camille 

 - INRIA (either the red or the black version):
![inr_logo_noir](https://github.com/acm-rep/2024/assets/5374264/bc2c12ca-5929-4c2f-a471-25aca199178a)
![inr_logo_rouge](https://github.com/acm-rep/2024/assets/5374264/9310d6a3-f368-49fd-9919-18f253f98035)

 - Brittany region
![RB_NB](https://github.com/acm-rep/2024/assets/5374264/38dc00e5-3ff2-4123-bcb0-40aa0a2a3002)

 - City of Rennes
![RENNES Métropole_noir](https://github.com/acm-rep/2024/assets/5374264/cfaaac2b-d07e-48b6-98be-4bf5b814af99)

 - University of Rennes
![Université RENNES_LOGOnoir](https://github.com/acm-rep/2024/assets/5374264/3033e1f6-c15a-41fa-b32f-8d2dafcb2c64)

**Comment by carlosmalt** [comment]
Thanks @cmaumet -- Do you want those added to the banner of the home page? Currently there is only the Université de Rennes logo. Or should I add them to the [sponsor page](https://acm-rep.github.io/2024/sponsor/)? If so, are there different sponsor levels?

**Comment by carlosmalt** [comment]
If you want those added to the home page banner, it would be good to have the logos in white since the background is dark.

**Comment by carlosmalt** [comment]
@cmaumet -- Please review #26.
