### ISSUE TITLE
Broken Rennes Tourist Info link 

### ISSUE THREAD

**Issue by carlosmalt** [acm-rep/2024#47]
On [Travel & Venue](https://acm-rep.github.io/2024/venue/), the [link](https://www.tourisme-rennes.com/en/) in the first paragraph doesn’t work.

**Comment by cmaumet** [comment]
Hum... not sure what's going on... the link seem to work fine for me?

**Comment by carlosmalt** [comment]
Interesting -- it does work on Firefox (Mac and iPhone) and Safari/Mac but not on Safari/iPhone. Might be a configuration problem on my iPhone.
