### ISSUE TITLE
Health and safety info

### ISSUE THREAD

**Issue by cmaumet** [acm-rep/2024#51]
Hi!

As discussed Edith and myself have been reviewing the info that we could include on the health and safety page. Edith found out that ACM conferences typically include the following 3 type of info:
 - Privacy Policy: https://www.acm.org/privacy-policy
 - Code of Ethics and Professional Conduct: https://www.acm.org/code-of-ethics
 - Policy Against Harassment at ACM Activities: https://www.acm.org/about-acm/policy-against-harassment

Is that something we can do as well for ACM REP?

**Comment by carlosmalt** [comment]
Thanks @cmaumet, I will include the above links in the [conduct](https://acm-rep.github.io/2024/conduct/) page. Anything you want to change/add to the [health](https://acm-rep.github.io/2024/health/) page?

**Comment by cmaumet** [comment]
LGTM on the conduct page. Thank you @carlosmalt!
