### ISSUE TITLE
Add sponsors name

### ISSUE THREAD

**Issue by cmaumet** [acm-rep/2024#69]
@TanuMalik would like to include name of the sponsors in addition to their logos: 

Here is a full list: Inria, Rennes Metropole, Region Bretagne, Université de Rennes and Sandia National Laboratory.

@msimonin would you be willing to create a PR for this?

**Comment by msimonin** [comment]
I'm on it here: https://github.com/msimonin/ACM-REP-2024/tree/dev/fix-69
