### ISSUE TITLE
Add sandia's logo

### ISSUE THREAD

**Issue by cmaumet** [acm-rep/2024#74]
We need to add the logo of sandia to the website as one of our sponsors. @gflofst: do you have a file that we can use?

**Comment by msimonin** [comment]
addition to #69

**Comment by msimonin** [comment]
Is this one ok ? 
https://commons.wikimedia.org/wiki/File:Sandia_National_Laboratories_logo.svg

**Comment by cmaumet** [comment]
LGTM, thanks!
