### ISSUE TITLE
Update registration closing and early bird dates 

### ISSUE THREAD

**Issue by cmaumet** [acm-rep/2024#75]
Discussed with Philippe and Edith. 

On the registration page (https://acm-rep.github.io/2024/registration/) it says: 

"""
Registration open: ~~early May~~ mid-May
Early-bird registration close: ~~May 19~~ May 31
Registration close: June 8
"""

but the early-bird deadline has been extended to June 8 and registration close to June 20.

@bclenet, @msimonin: can one of you propose an update with the new dates? 

The pages to modify are the following:
 - https://acm-rep.github.io/2024/registration/
 - https://acm-rep.github.io/2024/cfp/
 - https://acm-rep.github.io/2024/cft/
 - https://acm-rep.github.io/2024/cfposters/

**Comment by cmaumet** [comment]
Note : this has been started here: https://github.com/acm-rep/2024/pull/72 but is incomplete

**Comment by bclenet** [comment]
Hi, I'm starting to work on this issue.
