### ISSUE TITLE
Updating links to the hotels

### ISSUE THREAD

**Issue by cmaumet** [acm-rep/2024#79]
Following discussion with AJ Lauer and @gflofst as well as feedback from others, we need to updated the travel and venue page:
https://acm-rep.github.io/2024/venue/

 - currently each hotel link (e.g. Les Chouettes Hostel) goes to the main Destination Rennes page rather than the hotel itself.

we can either see if there is a specific page for the hotel on destination Rennes or remove the link altogether and keep a single link to Destination Rennes (separated from the hotel names).

ping: @bclenet @msimonin :)

**Comment by bclenet** [comment]
I am starting this one.
